name: Staging Build Workflow

on:
  push:
    branches:
      - "staging"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v3
      name: Set up Docker Buildx

    - uses: docker/login-action@v3
      name: Login to DockerHub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v6
      name: Build and Push WebApp Image
      id: docker_build
      with:
        context: .
        push: true
        tags: orgsinfo/webapp:latest
        file: Dockerfile.staging

    - name: WebApp Image Digest
      run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Deploy the webapp to the cluster
      uses: nickgronow/kubectl@master
      with:
        config_data: ${{ secrets.KUBE_CONFIG_DATA }}
        args: delete pod --selector="app=webapp-staging-app" --namespace=staging
